logging:
  config: classpath:logback-spring.xml
mybatis:
  config: classpath:mybatis-config.xml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infopublish?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0  
  jedis:
    pool:
      host: 127.0.0.1
      port: 6379
      timeout: 0
      config:
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis: 100000
server:
  port: 9090
  
task:
  execute:
    userScoreTask: 0 0 0 * * *
