package com.info.publish.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppUsersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public AppUsersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("nick_name is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("nick_name is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("nick_name =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("nick_name <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("nick_name >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("nick_name >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("nick_name <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("nick_name <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("nick_name like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("nick_name not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("nick_name in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("nick_name not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("nick_name between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("nick_name not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNull() {
            addCriterion("user_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNotNull() {
            addCriterion("user_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneEqualTo(String value) {
            addCriterion("user_phone =", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotEqualTo(String value) {
            addCriterion("user_phone <>", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThan(String value) {
            addCriterion("user_phone >", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_phone >=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThan(String value) {
            addCriterion("user_phone <", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_phone <=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLike(String value) {
            addCriterion("user_phone like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotLike(String value) {
            addCriterion("user_phone not like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIn(List<String> values) {
            addCriterion("user_phone in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotIn(List<String> values) {
            addCriterion("user_phone not in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneBetween(String value1, String value2) {
            addCriterion("user_phone between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotBetween(String value1, String value2) {
            addCriterion("user_phone not between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andImUuidIsNull() {
            addCriterion("im_uuid is null");
            return (Criteria) this;
        }

        public Criteria andImUuidIsNotNull() {
            addCriterion("im_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andImUuidEqualTo(String value) {
            addCriterion("im_uuid =", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidNotEqualTo(String value) {
            addCriterion("im_uuid <>", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidGreaterThan(String value) {
            addCriterion("im_uuid >", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidGreaterThanOrEqualTo(String value) {
            addCriterion("im_uuid >=", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidLessThan(String value) {
            addCriterion("im_uuid <", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidLessThanOrEqualTo(String value) {
            addCriterion("im_uuid <=", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidLike(String value) {
            addCriterion("im_uuid like", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidNotLike(String value) {
            addCriterion("im_uuid not like", value, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidIn(List<String> values) {
            addCriterion("im_uuid in", values, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidNotIn(List<String> values) {
            addCriterion("im_uuid not in", values, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidBetween(String value1, String value2) {
            addCriterion("im_uuid between", value1, value2, "imUuid");
            return (Criteria) this;
        }

        public Criteria andImUuidNotBetween(String value1, String value2) {
            addCriterion("im_uuid not between", value1, value2, "imUuid");
            return (Criteria) this;
        }

        public Criteria andUserImagePathIsNull() {
            addCriterion("user_image_path is null");
            return (Criteria) this;
        }

        public Criteria andUserImagePathIsNotNull() {
            addCriterion("user_image_path is not null");
            return (Criteria) this;
        }

        public Criteria andUserImagePathEqualTo(String value) {
            addCriterion("user_image_path =", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathNotEqualTo(String value) {
            addCriterion("user_image_path <>", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathGreaterThan(String value) {
            addCriterion("user_image_path >", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("user_image_path >=", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathLessThan(String value) {
            addCriterion("user_image_path <", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathLessThanOrEqualTo(String value) {
            addCriterion("user_image_path <=", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathLike(String value) {
            addCriterion("user_image_path like", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathNotLike(String value) {
            addCriterion("user_image_path not like", value, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathIn(List<String> values) {
            addCriterion("user_image_path in", values, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathNotIn(List<String> values) {
            addCriterion("user_image_path not in", values, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathBetween(String value1, String value2) {
            addCriterion("user_image_path between", value1, value2, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andUserImagePathNotBetween(String value1, String value2) {
            addCriterion("user_image_path not between", value1, value2, "userImagePath");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationIsNull() {
            addCriterion("real_name_authentication is null");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationIsNotNull() {
            addCriterion("real_name_authentication is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationEqualTo(Boolean value) {
            addCriterion("real_name_authentication =", value, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationNotEqualTo(Boolean value) {
            addCriterion("real_name_authentication <>", value, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationGreaterThan(Boolean value) {
            addCriterion("real_name_authentication >", value, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("real_name_authentication >=", value, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationLessThan(Boolean value) {
            addCriterion("real_name_authentication <", value, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationLessThanOrEqualTo(Boolean value) {
            addCriterion("real_name_authentication <=", value, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationIn(List<Boolean> values) {
            addCriterion("real_name_authentication in", values, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationNotIn(List<Boolean> values) {
            addCriterion("real_name_authentication not in", values, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationBetween(Boolean value1, Boolean value2) {
            addCriterion("real_name_authentication between", value1, value2, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameAuthenticationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("real_name_authentication not between", value1, value2, "realNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationIsNull() {
            addCriterion("bussiness_authentication is null");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationIsNotNull() {
            addCriterion("bussiness_authentication is not null");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationEqualTo(Boolean value) {
            addCriterion("bussiness_authentication =", value, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationNotEqualTo(Boolean value) {
            addCriterion("bussiness_authentication <>", value, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationGreaterThan(Boolean value) {
            addCriterion("bussiness_authentication >", value, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("bussiness_authentication >=", value, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationLessThan(Boolean value) {
            addCriterion("bussiness_authentication <", value, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationLessThanOrEqualTo(Boolean value) {
            addCriterion("bussiness_authentication <=", value, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationIn(List<Boolean> values) {
            addCriterion("bussiness_authentication in", values, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationNotIn(List<Boolean> values) {
            addCriterion("bussiness_authentication not in", values, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationBetween(Boolean value1, Boolean value2) {
            addCriterion("bussiness_authentication between", value1, value2, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andBussinessAuthenticationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("bussiness_authentication not between", value1, value2, "bussinessAuthentication");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumIsNull() {
            addCriterion("publish_info_num is null");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumIsNotNull() {
            addCriterion("publish_info_num is not null");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumEqualTo(Integer value) {
            addCriterion("publish_info_num =", value, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumNotEqualTo(Integer value) {
            addCriterion("publish_info_num <>", value, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumGreaterThan(Integer value) {
            addCriterion("publish_info_num >", value, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("publish_info_num >=", value, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumLessThan(Integer value) {
            addCriterion("publish_info_num <", value, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumLessThanOrEqualTo(Integer value) {
            addCriterion("publish_info_num <=", value, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumIn(List<Integer> values) {
            addCriterion("publish_info_num in", values, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumNotIn(List<Integer> values) {
            addCriterion("publish_info_num not in", values, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumBetween(Integer value1, Integer value2) {
            addCriterion("publish_info_num between", value1, value2, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andPublishInfoNumNotBetween(Integer value1, Integer value2) {
            addCriterion("publish_info_num not between", value1, value2, "publishInfoNum");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceIsNull() {
            addCriterion("account_banlance is null");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceIsNotNull() {
            addCriterion("account_banlance is not null");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceEqualTo(Double value) {
            addCriterion("account_banlance =", value, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceNotEqualTo(Double value) {
            addCriterion("account_banlance <>", value, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceGreaterThan(Double value) {
            addCriterion("account_banlance >", value, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceGreaterThanOrEqualTo(Double value) {
            addCriterion("account_banlance >=", value, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceLessThan(Double value) {
            addCriterion("account_banlance <", value, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceLessThanOrEqualTo(Double value) {
            addCriterion("account_banlance <=", value, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceIn(List<Double> values) {
            addCriterion("account_banlance in", values, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceNotIn(List<Double> values) {
            addCriterion("account_banlance not in", values, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceBetween(Double value1, Double value2) {
            addCriterion("account_banlance between", value1, value2, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andAccountBanlanceNotBetween(Double value1, Double value2) {
            addCriterion("account_banlance not between", value1, value2, "accountBanlance");
            return (Criteria) this;
        }

        public Criteria andVipIsNull() {
            addCriterion("vip is null");
            return (Criteria) this;
        }

        public Criteria andVipIsNotNull() {
            addCriterion("vip is not null");
            return (Criteria) this;
        }

        public Criteria andVipEqualTo(Boolean value) {
            addCriterion("vip =", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipNotEqualTo(Boolean value) {
            addCriterion("vip <>", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipGreaterThan(Boolean value) {
            addCriterion("vip >", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipGreaterThanOrEqualTo(Boolean value) {
            addCriterion("vip >=", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipLessThan(Boolean value) {
            addCriterion("vip <", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipLessThanOrEqualTo(Boolean value) {
            addCriterion("vip <=", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipIn(List<Boolean> values) {
            addCriterion("vip in", values, "vip");
            return (Criteria) this;
        }

        public Criteria andVipNotIn(List<Boolean> values) {
            addCriterion("vip not in", values, "vip");
            return (Criteria) this;
        }

        public Criteria andVipBetween(Boolean value1, Boolean value2) {
            addCriterion("vip between", value1, value2, "vip");
            return (Criteria) this;
        }

        public Criteria andVipNotBetween(Boolean value1, Boolean value2) {
            addCriterion("vip not between", value1, value2, "vip");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeIsNull() {
            addCriterion("vip_validity_time is null");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeIsNotNull() {
            addCriterion("vip_validity_time is not null");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeEqualTo(Date value) {
            addCriterion("vip_validity_time =", value, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeNotEqualTo(Date value) {
            addCriterion("vip_validity_time <>", value, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeGreaterThan(Date value) {
            addCriterion("vip_validity_time >", value, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("vip_validity_time >=", value, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeLessThan(Date value) {
            addCriterion("vip_validity_time <", value, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeLessThanOrEqualTo(Date value) {
            addCriterion("vip_validity_time <=", value, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeIn(List<Date> values) {
            addCriterion("vip_validity_time in", values, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeNotIn(List<Date> values) {
            addCriterion("vip_validity_time not in", values, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeBetween(Date value1, Date value2) {
            addCriterion("vip_validity_time between", value1, value2, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andVipValidityTimeNotBetween(Date value1, Date value2) {
            addCriterion("vip_validity_time not between", value1, value2, "vipValidityTime");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeIsNull() {
            addCriterion("android_device_code is null");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeIsNotNull() {
            addCriterion("android_device_code is not null");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeEqualTo(String value) {
            addCriterion("android_device_code =", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeNotEqualTo(String value) {
            addCriterion("android_device_code <>", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeGreaterThan(String value) {
            addCriterion("android_device_code >", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("android_device_code >=", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeLessThan(String value) {
            addCriterion("android_device_code <", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeLessThanOrEqualTo(String value) {
            addCriterion("android_device_code <=", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeLike(String value) {
            addCriterion("android_device_code like", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeNotLike(String value) {
            addCriterion("android_device_code not like", value, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeIn(List<String> values) {
            addCriterion("android_device_code in", values, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeNotIn(List<String> values) {
            addCriterion("android_device_code not in", values, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeBetween(String value1, String value2) {
            addCriterion("android_device_code between", value1, value2, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAndroidDeviceCodeNotBetween(String value1, String value2) {
            addCriterion("android_device_code not between", value1, value2, "androidDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeIsNull() {
            addCriterion("apple_device_code is null");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeIsNotNull() {
            addCriterion("apple_device_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeEqualTo(String value) {
            addCriterion("apple_device_code =", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeNotEqualTo(String value) {
            addCriterion("apple_device_code <>", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeGreaterThan(String value) {
            addCriterion("apple_device_code >", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("apple_device_code >=", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeLessThan(String value) {
            addCriterion("apple_device_code <", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeLessThanOrEqualTo(String value) {
            addCriterion("apple_device_code <=", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeLike(String value) {
            addCriterion("apple_device_code like", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeNotLike(String value) {
            addCriterion("apple_device_code not like", value, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeIn(List<String> values) {
            addCriterion("apple_device_code in", values, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeNotIn(List<String> values) {
            addCriterion("apple_device_code not in", values, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeBetween(String value1, String value2) {
            addCriterion("apple_device_code between", value1, value2, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andAppleDeviceCodeNotBetween(String value1, String value2) {
            addCriterion("apple_device_code not between", value1, value2, "appleDeviceCode");
            return (Criteria) this;
        }

        public Criteria andUserScoreIsNull() {
            addCriterion("user_score is null");
            return (Criteria) this;
        }

        public Criteria andUserScoreIsNotNull() {
            addCriterion("user_score is not null");
            return (Criteria) this;
        }

        public Criteria andUserScoreEqualTo(Long value) {
            addCriterion("user_score =", value, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreNotEqualTo(Long value) {
            addCriterion("user_score <>", value, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreGreaterThan(Long value) {
            addCriterion("user_score >", value, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreGreaterThanOrEqualTo(Long value) {
            addCriterion("user_score >=", value, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreLessThan(Long value) {
            addCriterion("user_score <", value, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreLessThanOrEqualTo(Long value) {
            addCriterion("user_score <=", value, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreIn(List<Long> values) {
            addCriterion("user_score in", values, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreNotIn(List<Long> values) {
            addCriterion("user_score not in", values, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreBetween(Long value1, Long value2) {
            addCriterion("user_score between", value1, value2, "userScore");
            return (Criteria) this;
        }

        public Criteria andUserScoreNotBetween(Long value1, Long value2) {
            addCriterion("user_score not between", value1, value2, "userScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_users
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 21 23:00:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}