package com.info.publish.domain;

import java.util.Date;

public class AppUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.user_id
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.nick_name
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.user_phone
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.user_password
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.im_uuid
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private String imUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.user_image_path
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private String userImagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.real_name_authentication
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Boolean realNameAuthentication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.bussiness_authentication
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Boolean bussinessAuthentication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.publish_info_num
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Integer publishInfoNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.account_banlance
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Double accountBanlance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.vip
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Boolean vip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.vip_validity_time
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Date vipValidityTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.android_device_code
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private String androidDeviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.apple_device_code
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private String appleDeviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_users.user_score
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    private Long userScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.user_id
     *
     * @return the value of app_users.user_id
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.user_id
     *
     * @param userId the value for app_users.user_id
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.nick_name
     *
     * @return the value of app_users.nick_name
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.nick_name
     *
     * @param nickName the value for app_users.nick_name
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.user_phone
     *
     * @return the value of app_users.user_phone
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.user_phone
     *
     * @param userPhone the value for app_users.user_phone
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.user_password
     *
     * @return the value of app_users.user_password
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.user_password
     *
     * @param userPassword the value for app_users.user_password
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.im_uuid
     *
     * @return the value of app_users.im_uuid
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getImUuid() {
        return imUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.im_uuid
     *
     * @param imUuid the value for app_users.im_uuid
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setImUuid(String imUuid) {
        this.imUuid = imUuid == null ? null : imUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.user_image_path
     *
     * @return the value of app_users.user_image_path
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getUserImagePath() {
        return userImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.user_image_path
     *
     * @param userImagePath the value for app_users.user_image_path
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setUserImagePath(String userImagePath) {
        this.userImagePath = userImagePath == null ? null : userImagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.real_name_authentication
     *
     * @return the value of app_users.real_name_authentication
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Boolean getRealNameAuthentication() {
        return realNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.real_name_authentication
     *
     * @param realNameAuthentication the value for app_users.real_name_authentication
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setRealNameAuthentication(Boolean realNameAuthentication) {
        this.realNameAuthentication = realNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.bussiness_authentication
     *
     * @return the value of app_users.bussiness_authentication
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Boolean getBussinessAuthentication() {
        return bussinessAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.bussiness_authentication
     *
     * @param bussinessAuthentication the value for app_users.bussiness_authentication
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setBussinessAuthentication(Boolean bussinessAuthentication) {
        this.bussinessAuthentication = bussinessAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.publish_info_num
     *
     * @return the value of app_users.publish_info_num
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Integer getPublishInfoNum() {
        return publishInfoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.publish_info_num
     *
     * @param publishInfoNum the value for app_users.publish_info_num
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setPublishInfoNum(Integer publishInfoNum) {
        this.publishInfoNum = publishInfoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.account_banlance
     *
     * @return the value of app_users.account_banlance
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Double getAccountBanlance() {
        return accountBanlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.account_banlance
     *
     * @param accountBanlance the value for app_users.account_banlance
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setAccountBanlance(Double accountBanlance) {
        this.accountBanlance = accountBanlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.vip
     *
     * @return the value of app_users.vip
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Boolean getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.vip
     *
     * @param vip the value for app_users.vip
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setVip(Boolean vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.vip_validity_time
     *
     * @return the value of app_users.vip_validity_time
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Date getVipValidityTime() {
        return vipValidityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.vip_validity_time
     *
     * @param vipValidityTime the value for app_users.vip_validity_time
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setVipValidityTime(Date vipValidityTime) {
        this.vipValidityTime = vipValidityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.android_device_code
     *
     * @return the value of app_users.android_device_code
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getAndroidDeviceCode() {
        return androidDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.android_device_code
     *
     * @param androidDeviceCode the value for app_users.android_device_code
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setAndroidDeviceCode(String androidDeviceCode) {
        this.androidDeviceCode = androidDeviceCode == null ? null : androidDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.apple_device_code
     *
     * @return the value of app_users.apple_device_code
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public String getAppleDeviceCode() {
        return appleDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.apple_device_code
     *
     * @param appleDeviceCode the value for app_users.apple_device_code
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setAppleDeviceCode(String appleDeviceCode) {
        this.appleDeviceCode = appleDeviceCode == null ? null : appleDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_users.user_score
     *
     * @return the value of app_users.user_score
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public Long getUserScore() {
        return userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_users.user_score
     *
     * @param userScore the value for app_users.user_score
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    public void setUserScore(Long userScore) {
        this.userScore = userScore;
    }
}