package com.info.publish.mapper;

import com.info.publish.domain.AppUsers;
import com.info.publish.domain.AppUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AppUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    long countByExample(AppUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    int deleteByExample(AppUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    @Delete({
        "delete from app_users",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    @Insert({
        "insert into app_users (user_id, nick_name, ",
        "user_phone, user_password, ",
        "im_uuid, user_image_path, ",
        "real_name_authentication, bussiness_authentication, ",
        "publish_info_num, account_banlance, ",
        "vip, vip_validity_time, ",
        "android_device_code, apple_device_code, ",
        "user_score)",
        "values (#{userId,jdbcType=BIGINT}, #{nickName,jdbcType=VARCHAR}, ",
        "#{userPhone,jdbcType=VARCHAR}, #{userPassword,jdbcType=VARCHAR}, ",
        "#{imUuid,jdbcType=VARCHAR}, #{userImagePath,jdbcType=VARCHAR}, ",
        "#{realNameAuthentication,jdbcType=BIT}, #{bussinessAuthentication,jdbcType=BIT}, ",
        "#{publishInfoNum,jdbcType=INTEGER}, #{accountBanlance,jdbcType=DOUBLE}, ",
        "#{vip,jdbcType=BIT}, #{vipValidityTime,jdbcType=TIMESTAMP}, ",
        "#{androidDeviceCode,jdbcType=VARCHAR}, #{appleDeviceCode,jdbcType=VARCHAR}, ",
        "#{userScore,jdbcType=BIGINT})"
    })
    int insert(AppUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    int insertSelective(AppUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    List<AppUsers> selectByExample(AppUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    @Select({
        "select",
        "user_id, nick_name, user_phone, user_password, im_uuid, user_image_path, real_name_authentication, ",
        "bussiness_authentication, publish_info_num, account_banlance, vip, vip_validity_time, ",
        "android_device_code, apple_device_code, user_score",
        "from app_users",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    @ResultMap("com.info.publish.mapper.AppUsersMapper.BaseResultMap")
    AppUsers selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppUsers record, @Param("example") AppUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    int updateByExample(@Param("record") AppUsers record, @Param("example") AppUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    int updateByPrimaryKeySelective(AppUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_users
     *
     * @mbg.generated Tue Aug 21 23:00:45 CST 2018
     */
    @Update({
        "update app_users",
        "set nick_name = #{nickName,jdbcType=VARCHAR},",
          "user_phone = #{userPhone,jdbcType=VARCHAR},",
          "user_password = #{userPassword,jdbcType=VARCHAR},",
          "im_uuid = #{imUuid,jdbcType=VARCHAR},",
          "user_image_path = #{userImagePath,jdbcType=VARCHAR},",
          "real_name_authentication = #{realNameAuthentication,jdbcType=BIT},",
          "bussiness_authentication = #{bussinessAuthentication,jdbcType=BIT},",
          "publish_info_num = #{publishInfoNum,jdbcType=INTEGER},",
          "account_banlance = #{accountBanlance,jdbcType=DOUBLE},",
          "vip = #{vip,jdbcType=BIT},",
          "vip_validity_time = #{vipValidityTime,jdbcType=TIMESTAMP},",
          "android_device_code = #{androidDeviceCode,jdbcType=VARCHAR},",
          "apple_device_code = #{appleDeviceCode,jdbcType=VARCHAR},",
          "user_score = #{userScore,jdbcType=BIGINT}",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AppUsers record);
}